name: Generate new footprint release package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pip and pipenv
        run: |
          sudo apt-get update -y && sudo apt-get install python3-pip -y
          pip install --user pipenv

      - name: Setup submodules and python dependencies
        run: make deps

      - name: Generate footprints
        run: make build

      - name: Create archive
        run: |
          cp LICENSE README.md generated/
          cd generated/
          tar czfv "cutie-lib-${GITHUB_REF#refs/*/}.tar.gz" *

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "generated/*.tar.gz"
