name: Generate new footprint release package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: build and release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Setup python dependencies
        run: uv sync

      - name: Check formatting
        run: uv run ruff check

      - name: Generate footprints
        run: ./util/build-lib.sh

      - name: Create archive
        run: |
          cp LICENSE README.md generated/
          cd generated/
          tar czfv "MCKRL-${GITHUB_REF#refs/*/}.tar.gz" *

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "generated/*.tar.gz"
